###
## M5Stack atom S3 lite board powered by 12VDC/GND connection to 24VDC/GND from Brink, in combination with this base from m5stack:
## https://shop.m5stack.com/products/atomic-rs485-base
## NOTE: there are other RS485 boards from m5stack, these are not tested (like the tail-rs485)
#
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# uart for modbus rtu  FACTORY ZERO EDITION!
uart:
  id: mod_bus
  baud_rate: 9600  
  stop_bits: 1
  parity: even
  tx_pin: GPIO6
  rx_pin: GPIO5

# i2c for extra sensor
i2c:
  - id: bus_a
    sda: GPIO2
    scl: GPIO1

###  ESP restart button
button:
  - platform: restart
    id: restart_button
    name: Restart
    
# Enable/Disable logging
logger:
  logs:
    modbus_controller.sensor: WARN
    modbus_controller.output: WARN
    modbus.number: WARN
    esp32.preferences: WARN
    sensor: WARN
    text_sensor: WARN
    dht.sensor: WARN
    switch: WARN
    button: WARN
    number: WARN
  # baud_rate: 0  # <--- super important! for ESP8266

wifi:
  ap:
    ssid: "${friendly_name}"
    password: "configesp"

  
captive_portal:

# Enable Web server.
web_server:
  port: 80
