number:
# Maximum value for Flair 225 is 225m3/h
  - id: brink_modbus_flow_rate
    name: ${brink_modbus_flow_rate}
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding
    address: 8002
    value_type: S_WORD      
    min_value: 0
    max_value: 225
    mode: slider

  - id: brink_flow_0
    name: Flow 0
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding
    address: 6000
    unit_of_measurement: "m3/h"
    value_type: S_WORD      
    min_value: 0
    max_value: 225
    mode: slider
    icon: mdi:fan-auto

  - id: brink_flow_1
    name: Flow 1
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding
    address: 6001
    unit_of_measurement: "m3/h"
    value_type: S_WORD      
    min_value: 50
    max_value: 225
    mode: slider
    icon: mdi:fan-speed-1

  - id: brink_flow_2
    name: Flow 2
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding
    address: 6002
    unit_of_measurement: "m3/h"
    value_type: S_WORD      
    min_value: 50
    max_value: 225
    mode: slider
    icon: mdi:fan-speed-2

  - id: brink_flow_3
    name: Flow 3
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding
    address: 6003
    unit_of_measurement: "m3/h"
    value_type: S_WORD   
    min_value: 50
    max_value: 225
    mode: slider
    icon: mdi:fan-speed-3
