substitutions:
  name: brink
  friendly_name: Brink
  device_description: "Esphome component for Brink Flair with modbus"
  timezone: "Europe/Amsterdam"
###  Settings Brink Flair (no need to change normally)
###  menu 14-Communication: TypeBus=Modbus, Slave modbusaddress=20, Baudrate=19200, Parity=Even
  modbusaddress: "20"

# In order to use other language or a different ESP chip, fix include file name below:
# Currently supported languages are en, nl. 
# ESP32 is a mh-et-live or wemos d32 mini, esp8266 is a wemos d1 mini, esp32s3 is a lilygo ESP32S3-T7
# Be carefull not to upload the wrong code to the wrong chip. This could brick your ESP chip.
# Choose the correct type for your Brink model, so the correct max flow can be setup with a slider.

packages:
  remote_package:
    url: https://github.com/fonske/Brink-flair-modbus
    ref: main
    refresh: 0s
    files: [ esphome/type/brink-325.yaml,
             esphome/labels/.brink-labels-en.yaml, 
             esphome/.brink.base.yaml, 
             esphome/boards/board-m5stack-atoms3-lite.yaml,
#             esphome/sensors/sensor-enviii-i2c-m5stack.yaml,
#             esphome/sensors/sensor-brink_hum_sensor.yaml,
#             esphome/sensors/sensor-brink_co2_1_sensor.yaml
           ]
    ## options are:
      # esphome/type/.brink-300.yaml
      # esphome/type/.brink-325.yaml
      # esphome/type/.brink-400.yaml
      # esphome/type/.brink-450.yaml
      # esphome/type/.brink-600.yaml
      # esphome/labels/.brink-labels-en.yaml
      # esphome/labels/.brink-labels-nl.yaml
      # esphome/.brink.base.yaml
      # esphome/boards/board-esp32.yaml
      # esphome/boards/board-esp32S3.yaml
      # esphome/boards/board-esp8266.yaml
      # esphome/boards/board-esp8266-d1-mini-pro.yaml
      # esphome/boards/board-m5stack-atom
      # esphome/boards/board-m5stack-atom-ttl.yaml
      # esphome/boards/board-m5stack-atoms3-lite
      # esphome/sensors/sensor-scd41-i2c-dfrobot.yaml
      # esphome/sensors/sensor-scd41-i2c-m5stack.yaml
      # esphome/sensors/sensor-enviii-i2c-m5stack.yaml
      # esphome/sensors/sensor-enviv-i2c-m5stack.yaml
      # esphome/sensors/sensor-dht22.yaml
      # esphome/sensors/sensor-brink_hum_sensor.yaml
      # esphome/sensors/sensor-brink_co2_1_sensor.yaml
      # esphome/sensors/sensor-brink_co2_2_sensor.yaml
      # esphome/sensors/sensor-brink_co2_3_sensor.yaml
      # esphome/sensors/sensor-brink_co2_4_sensor.yaml

# for developing/testing, uncomment local includes and comment out remote_package part.
# packages:
#   substitutions: !include labels/.brink-labels-en.yaml
#   device_base1: !include .brink.base.yaml
#   device_base2: !include boards/board-esp8266.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Put your API key here if you have one, if not leave it as it is.
# api:
#   encryption:
#     key: !secret brink_api_key
